### ISSUE TITLE
Extract point or timeseries from raster

### ISSUE THREAD

**Issue by kickapoo** [openmeteo/pthelma#17]
Iam running the following script: 

```python
import os
import glob
from osgeo import ogr, osr
from pthelma.spatial import (extract_point_from_raster,
			                     extract_point_timeseries_from_rasters)
# Data Cache One file path
file = os.path.join(os.path.dirname(__file__),"meteo_data/daily_rain-2014-12-01.tif") 
# Data Cache multi files
files = glob.glob(os.path.join(os.path.dirname(__file__),"meteo_data/daily_rain*.tif"))
# Lat/Long of Arta City
lat = 20.98333 
long = 39.15
# Creating Point
point = ogr.Geometry(ogr.wkbPoint)
sr = osr.SpatialReference()
sr.ImportFromEPSG(4326)
point.AssignSpatialReference(sr)
point.AddPoint(lat, long)
# Extract One Point 
extracted_point = extract_point_from_raster(file, point)
# Extract Timeseries
extracted_timeseries = extract_point_timeseries_from_rasters(files, point)
```

The above code produce the following errors:
1. In the case of one Point
```python
File "/usr/local/lib/python2.7/dist-packages/pthelma/spatial.py", line 179, in extract_point_from_raster
    point_sr = point.GetSpatialReference()
AttributeError: 'list' object has no attribute 'GetSpatialReference'
```
2. In the case of a Timeseries
```python
ERROR 5: meteo_data/daily_rain-2014-12-01.tif, band 1: Access window out of range in RasterIO().  Requested
(26694,27908) of size 1x1 on raster of 461x420.
Traceback (most recent call last):
  File "spatial_test.py", line 29, in <module>
    extracted_timeseries = extract_point_timeseries_from_rasters(files, point)
  File "/usr/local/lib/python2.7/dist-packages/pthelma/spatial.py", line 218, in extract_point_timeseries_from_rasters
    value = extract_point_from_raster(point, fp)
  File "/usr/local/lib/python2.7/dist-packages/pthelma/spatial.py", line 195, in extract_point_from_raster
    result = struct.unpack('f', structval)[0]
struct.error: unpack requires a string argument of length 4
```

**Comment by aptiko** [comment]
That script has errors, particularly in the way it calls `extract_point_from_raster`. Here is a corrected script:

```python
import glob
import os

from osgeo import gdal, ogr, osr

from pthelma.spatial import (extract_point_from_raster,
                             extract_point_timeseries_from_rasters)

# Data Cache One file path
file = os.path.join(os.path.dirname(__file__), "daily_rain-2014-12-01.tif")

# Data Cache multi files
files = glob.glob(os.path.join(os.path.dirname(__file__), "daily_rain*.tif"))

# Lat/Long of Arta City
long = 20.98333
lat = 39.15

# Create point
point = ogr.Geometry(ogr.wkbPoint)
sr = osr.SpatialReference()
sr.ImportFromEPSG(4326)
point.AssignSpatialReference(sr)
point.AddPoint(long, lat)

# Extract One Point
f = gdal.Open(file)
extracted_point = extract_point_from_raster(point, f)
print extracted_point

# Extract Timeseries
extracted_timeseries = extract_point_timeseries_from_rasters(files, point)
print extracted_timeseries
```

This one does not produce any error here, at least not if the only file in the directory is `daily_rain-2014-12-01.tif`.

**Comment by kickapoo** [comment]
Sorry about that. Please update pthlema documentation  with correct
example. The script is based on that.

**Comment by aptiko** [comment]
Which example is wrong?

**Comment by kickapoo** [comment]
At pthlema.spatial documentation, at the end of the page (Usage example) misses the `f = gdal.Open(file)`

**Comment by aptiko** [comment]
That example is about a different function, `extract_point_timeseries_from_rasters`.

**Comment by kickapoo** [comment]
Documentation of `extract_point_from_raster` states that "data_source is a GDAL raster, and point is an OGR point object.".  In the script, my file is a geotif (or whatever is called) and i assume that is GDAL raster as is provided by opemeteo.
That said,  my initial script is under documentation suggestions and `f = gdal.Open(file)` couldn't be assumed.

Also, `extract_point_timeseries_from_rasters` and `extract_point_from_raster` are similiar functions and usage example should be near the same in both cases. Reading one or multiple files should not be so important.

Finally, a charge behavior that i cant even imagine what might be. 
Updating my initial `.py` script within `debian-bitia-bundle` environment  still produce the errors i wrote.  Rewriting the same code and storing `.py` in another file no errors occur.
